#!/bin/sh

FILES="profile bashrc bash_profile editrc inputrc gitconfig vimrc vim ctags 
       tmux.conf shinit config"

for fname in $FILES ; do
    # use -n not -h for gnu compat
    ln -fsn "$PWD/${fname}" "${HOME}/.${fname}"
done
