#!/bin/sh

CONFIG=config
FILES="profile bashrc bash_profile editrc inputrc gitconfig vimrc vim ctags 
       tmux.conf shrc config/git terminfo"

mkdir -p "${HOME}/.${CONFIG}"
for fname in $FILES ; do
    # use -n not -h for gnu compat
    ln -fsn "$PWD/${fname}" "${HOME}/.${fname}"
done

# TODO temporary cleanup from rename .shinit to .shrc
rm -f "${HOME}/.shinit"
